### ISSUE TITLE
bug: Remove received push notifications doesn't work

### ISSUE THREAD

**Issue by mtnair** [robingenz/capacitor-firebase#103]
**Plugin(s):** Messaging

**Platform(s):** Android (couldn't verify iOS yet)

**Current behavior:**
I'm trying this library because the `@capacitor/push-notifications` plugin [doesn't support data-only push notifications](https://capacitorjs.com/docs/apis/push-notifications#silent-push-notifications-data-only-notifications).
My messages to the app look something like this (output from event `notificationReceived`):
```json
{
    "id": "0:1654783107630987%e07b2503f9fd7ecd",
    "data": {
        "Message": "IV6J9EcYqZejFvsOJLMaaA=="
    }
}
```
The content in `data['Message']` is encrypted and I want to decrypt it before showing the notification (via `@capacitor/local-notifications`).
First of all, this plugin (`@capacitor-firebase/messaging`) shows the notification in the same way the official plugin (`@capacitor/push-notifications`) does, even though it neither has a title nor a body. This would be no problem, if I could remove the notification from the screen immediately after I receive it. But when listening to the event `notificationReceived`, and trying to remove the notification using the following code, the Android app terminates because of an unhandled exception, when trying to cast the notification id string to an int (see stack trace at the end of the report):
```ts
FirebaseMessaging.addListener('notificationReceived', async (event) => {
    FirebaseMessaging.removeDeliveredNotifications({
        ids: [event.notification.id]
    });
});
```
The type definition of `removeDeliveredNotifications` says, it expects an array of strings of ids to remove the notifications:
```ts
export interface RemoveDeliveredNotificationsOptions {
    /**
     * @since 0.2.2
     */
    ids: string[];
}
```
The notification id I get from the event is also a string (e.g. "0:1654783107630987%e07b2503f9fd7ecd"). But when I use `FirebaseMessaging.getDeliveredNotifications()` to get delivered notifications, the id in the notification object is actually a number (contrary to the type definition, where it says it is a string):
```json
{
    "id": 0,
    "title": "[App Name] Message",
    "body": "IV6J9EcYqZejFvsOJLMaaA==",
    "data": {
        "android.title": "[App Name] Message",
        "android.reduced.images": true,
        "android.template": "android.app.Notification$BigTextStyle",
        "android.showChronometer": false,
        "android.text": "IV6J9EcYqZejFvsOJLMaaA==",
        "android.progress": 0,
        "android.progressMax": 0,
        "android.appInfo": "ApplicationInfo{ed3475f com.example.app}",
        "android.showWhen": true,
        "android.bigText": "IV6J9EcYqZejFvsOJLMaaA==",
        "android.progressIndeterminate": false
    }
}
```
Type definition of `Notification`:
```ts
export interface Notification {
    /**
     * The notification identifier.
     *
     * @since 0.2.2
     */
    id?: string;
}
```

Also, when I send multiple Notifications to the app, the id _string_ always begins with `0:` and the id _number_ from delivered notifications is always `0`. So I can't simply use the prefix from the id string to identify the correct notification.

**Expected behavior:**
`removeDeliveredNotifications` should either correctly accept string ids or delivered notification ids should be unique numbers.

**Steps to reproduce:**

See code.

**Related code:**
```ts
FirebaseMessaging.addListener('notificationReceived', async (event) => {
    const deliveredNotifications = await FirebaseMessaging.getDeliveredNotifications();
    const deliveredNotification = deliveredNotifications.notifications.find((n) => n.id === event.notification.id);

    // either
    FirebaseMessaging.removeDeliveredNotifications({
        ids: [event.notification.id]
    });
    // or
    FirebaseMessaging.removeDeliveredNotifications({
        ids: [deliveredNotification.id]
    });

    // send local notification afterwards
    LocalNotifications.schedule({
        notifications: [
            {
                id: 1234,
                title: '[App name]',
                body: 'message'
            }
        ]
    })
})
```
Stack trace on Android:
```
2022-06-09 15:27:04.547 29471-29586/com.example.app E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:598)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at dev.robingenz.capacitorjs.plugins.firebase.messaging.FirebaseMessaging.removeDeliveredNotifications(FirebaseMessaging.java:58)
        at dev.robingenz.capacitorjs.plugins.firebase.messaging.FirebaseMessagingPlugin.removeDeliveredNotifications(FirebaseMessagingPlugin.java:129)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:598) 
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Other information:**

**Capacitor doctor:**
```
$ npx cap doctor
   Capacitor Doctor   

Latest Dependencies:       

  @capacitor/cli: 3.5.1    
  @capacitor/core: 3.5.1   
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1    

Installed Dependencies:    

  @capacitor/cli: 3.5.1    
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.4.3    
  @capacitor/core: 3.5.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

**Comment by robingenz** [comment]
I just tested data-only push notifications and it seems to work on my device (OnePlus 7T, Android 11).
No notification is displayed (either with or without title/body) and the JS event fires.
Make sure to use the FCM REST API (not Firebase Dashboard).
This is my request body (`POST https://fcm.googleapis.com/fcm/send`):

```json
{
    "data": {
        "my_custom_key": "my_custom_value",
        "my_custom_key2": true
     },
    "to": "YOUR_TOKEN"
}
```

About the other: I could reproduce the issues with the typescript definitions and the crash. I will fix it.

**Comment by robingenz** [comment]
You can give it a try: 
```
npm i @capacitor-firebase/messaging@0.3.1-dev.857e322.1655063808
```

**Comment by robingenz** [comment]
@mtnair  Have you tested it and does the problem still exist?

**Comment by mtnair** [comment]
Sorry for the late reply, I couldn't test it until today. The problem with the type definitions is indeed fixed.

I also identified a problem on our backend side, we sent two push messages simultaneously to our apps, one "classic" notification with title and body, and one data-only notification. But it took a while until I found out about this, because 1. I'm no backend developer and didn't know about this behavior, and 2. the `notificationReceived` event only seems to trigger for the data-only notification.
So the classic title-body notification popped up in the notification center, and the data-only notification went through my decryption process in the event listener. But because the first notification didn't went through the listener, I thought it was only one notification. I don't know if this is a problem with your library, because I also tried it with `@capacitor/push-notifications`, where it behaves the same.

Also deleting notifications seems a little bit odd, because the classic title-body notifications always seem to have the id "0", might this be a problem on our side too? Is it possible to manually specify the notification id before sending the notification? I thought this id would be automatically assigned either by FCM or the device.

**Comment by robingenz** [comment]
> But because the first notification didn't went through the listener, I thought it was only one notification. I don't know if this is a problem with your library, because I also tried it with @capacitor/push-notifications, where it behaves the same.

This is not a problem with the library. In the background only data-only notifications can trigger `notificationReceived`.

> Also deleting notifications seems a little bit odd, because the classic title-body notifications always seem to have the id "0", might this be a problem on our side too?

You have to combine `id` and `tag`. `tag` is a new property in the dev version i recently published (see [here](https://github.com/robingenz/capacitor-firebase/issues/103#issuecomment-1153278238)). 
To remove a notification, just pass in the entire notification and the plugin will take the information it needs (see new typescript definitions for the method).

> Is it possible to manually specify the notification id before sending the notification?

No

**Comment by robingenz** [comment]
Have you tested the dev version and does everything work with it now?

**Comment by mtnair** [comment]
> This is not a problem with the library. In the background only data-only notifications can trigger `notificationReceived`.

So there is no other way to intercept other notifications in the app? And could you add a bit of documentation, that this event isn't triggered by these notifications?

> You have to combine `id` and `tag`. `tag` is a new property in the dev version i recently published (see [here](https://github.com/robingenz/capacitor-firebase/issues/103#issuecomment-1153278238)).
> To remove a notification, just pass in the entire notification and the plugin will take the information it needs (see new typescript definitions for the method).

> Have you tested the dev version and does everything work with it now?

This works now on android. I came to test it on iOS today too, but there, delivered notifications still don't get removed.

**Comment by robingenz** [comment]
> So there is no other way to intercept other notifications in the app? 

You should be able to list all active notifications with `getDeliveredNotifications`. But the listener fires in the background only for data-only notifications.

> And could you add a bit of documentation, that this event isn't triggered by these notifications?

Yes 👍 

> This works now on android. I came to test it on iOS today too, but there, delivered notifications still don't get removed.

Okay, then i will have a look at iOS next.

**Comment by robingenz** [comment]
Okay, iOS is fixed: 

```
npm i @capacitor-firebase/messaging@0.3.1-dev.50802e1.1655753859
```
