### ISSUE TITLE
feat: Update FBSDK to  11.2.0 or greater 

### ISSUE THREAD

**Issue by typefox09** [robingenz/capacitor-firebase#112]
**Is your feature request related to a problem? Please describe:**
Due to major changes in iOS 14 (relating to AppTrackingTransparency), Facebook has introduced a new feature "Aggregated Event Management". This helps to us to still record conversion events while maintaining user privacy. 

To set up Aggregated Event Measurement for app events we must:
"Update to Facebook SDK for iOS version 11.2.0 or above"

**Describe the solution you'd like:**
Update the FBSDK to version 11.2.0 or above

FB article for reference: https://www.facebook.com/business/help/331612538028890?id=428636648170202

**Comment by robingenz** [comment]
Hi @typefox09,

you can give it a try: 
```
npm i @capacitor-firebase/authentication@0.3.1-dev.83af7e4.1655271168
```

**Comment by typefox09** [comment]
Hi Robingenz, thanks for the fast response. I've installed the updated package, however now when I run `npx cap update ios` I get the following error:

[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "Firebase/Auth":
        In Podfile:
        CapacitorFirebaseAuthentication/Facebook (from `../../node_modules/@capacitor-firebase/authentication`) was
        resolved to 0.3.1-dev.83af7e4.1655271168, which depends on
        Firebase/Auth (= 9.1.0)
        
        None of your spec sources contain a spec satisfying the dependency: `Firebase/Auth (= 9.1.0)`.
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.

**Comment by robingenz** [comment]
You need to update your local pods repo. Please run `pod install --repo-update` in the `ios/App/` directory.

**Comment by typefox09** [comment]
That gives the following error:

[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport (from `../../node_modules/@capacitor-firebase/analytics`) was resolved to 0.2.2, which depends on
      Firebase/AnalyticsWithoutAdIdSupport (= 8.13.0) was resolved to 8.13.0, which depends on
        Firebase/CoreOnly (= 8.13.0)

    CapacitorFirebaseAuthentication/Facebook (from `../../node_modules/@capacitor-firebase/authentication`) was resolved to 0.3.1, which depends on
      Firebase/Auth (= 9.1.0) was resolved to 9.1.0, which depends on
        Firebase/CoreOnly (= 9.1.0)

**Comment by robingenz** [comment]
Okay, please update all other `@capacitor-firebase` packages to `0.3.1`.

**Comment by typefox09** [comment]
That works perfectly. Thanks for your help and timely update Robingenz.
