### ISSUE TITLE
bug: warning " > @capacitor-firebase/messaging@0.3.1" has incorrect peer dependency "firebase@^9.0.0"

### ISSUE THREAD

**Issue by serascandia** [robingenz/capacitor-firebase#118]
**Plugin(s):**
Messaging

**Platform(s):**
IOS

**Current behavior:**
when I try to install the package with YARN I got this warning message, this is normal?

**command run: yarn add @capacitor-firebase/messaging**

**Expected behavior:**
install the package without warnigs

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Hi @serascandia,
Unfortunately, I have no experience with yarn. It seems to be a general warning, which can also occur with other packages. Please post your question best on Stackoverflow. Since it is just a warning, I am closing this issue.
