### ISSUE TITLE
feat: automatically set current screen

### ISSUE THREAD

**Issue by jongbonga** [robingenz/capacitor-firebase#124]
**Is your feature request related to a problem? Please describe:**
Not a problem but a nice to have add-on that would automatically set the screenName according to route path or name

**Describe the solution you'd like:**
```
 ionViewDidEnter() {
    FirebaseAnalytics.setCurrentScreen({
      screenName: 'FirebaseAnalyticsPage',
    });
 }
```

Instead of calling the above snippet on every page, we could call something like `FirebaseAnalytics.trackPage({route: 'path'| 'name'})` on app load

**Comment by robingenz** [comment]
I think this is out-of-scope of this plugin. If I understand your proposal correctly, then it also depends on which framework you use. The Angular router works differently than the VueJs router etc. And these should trigger the event in case of navigation.
For this reason, I am closing this issue.
Please let me know if I missed something.

If you listen to the router events in a service, then you usually don't need the code on each page but only in the service. You could define the method options via route parameters or a predefined hash map etc.
