### ISSUE TITLE
feat: support Firebase Local Emulator

### ISSUE THREAD

**Issue by tlebeitsuk** [robingenz/capacitor-firebase#19]
**Is your feature request related to a problem? Please describe:**

[Firebase Local Emulator](https://firebase.google.com/docs/emulator-suite) is not currently supported.

**Describe the solution you'd like:**

iOS

```
#if DEBUG
     Auth.auth().useEmulator(withHost:config.devIP, port:9099)
#endif
```

Android
```
String devIP = this.config.getDevIP();

if(BuildConfig.DEBUG) {
     FirebaseAuth.getInstance().useEmulator(devIP, 9099);
}
```

**Comment by robingenz** [comment]
Hi @tlebeitsuk,
Thank you for your request! I will have a look at it!

**Comment by robingenz** [comment]
Hi @tlebeitsuk,
You can try it out if you want (dev build): 
```
npm i @capacitor-firebase/authentication@0.1.1-dev.62d5d5f.1647985256
```

Docs: https://github.com/robingenz/capacitor-firebase/blob/62d5d5ff067cebf175786dafbc082d3931366668/packages/authentication/README.md#useemulator
