### ISSUE TITLE
feat(authentication): password authentication

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-firebase#27]
**Is your feature request related to a problem? Please describe:**

You can use Firebase Authentication to let your users authenticate with Firebase using their email addresses and passwords ([password-auth](https://firebase.google.com/docs/auth/android/password-auth)). This is currently not possible with this plugin.

**Describe the solution you'd like:**

Add support for password authentication.

- createUserWithEmailAndPassword
- signInWithEmailAndPassword
- updateEmail
- sendEmailVerification
- sendPasswordResetEmail
- updatePassword

**Describe alternatives you've considered:**

No alternative solutions.

**Comment by m8xp0w3r** [comment]
This feature would be awesome.

**Comment by robingenz** [comment]
The first dev version is ready. It would be great if someone could support me with testing.
I am happy about any feedback!

```
npm i @capacitor-firebase/authentication@0.2.1-dev.9266910.1651091204
```

**Comment by robingenz** [comment]
Here you can find the new methods: https://github.com/robingenz/capacitor-firebase/blob/9266910503d371b3e6b5f65a681730bdacc3c5df/packages/authentication/README.md#api
