### ISSUE TITLE
bug(authentication): Facebook login accessToken is undefined

### ISSUE THREAD

**Issue by mostafa3ly** [robingenz/capacitor-firebase#31]
**Plugin version:**

@robingenz/capacitor-firebase-authentication ^0.4.1

**Platform(s):**

Android
iOS

**Current behavior:**

Facebook sign in is successfully done when calling `signInWithFacebook()` but the result is an object of `{prodvider: ... , idToken: ...}` 
and there is no accessToken returned in the result which is needed to link native layer with JS sdk by calling `signInWithCredintials()`
described [here ](https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/firebase-js-sdk.md)

**Expected behavior:**

accessToken returned in `signinWithFacebook()` result to use it in JS sdk signin

**Steps to reproduce:**

**Related code:**

```
  const result = await FirebaseAuthentication.signInWithFacebook();
  const credential = FacebookAuthProvider.credential(result.credential?.accessToken);
  const auth = getAuth();
  await signInWithCredential(auth, credential);
```

**Other information:**

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

Installed Dependencies:

  @capacitor/cli: 3.4.1
  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.1
  @capacitor/ios: 3.4.1

[success] Android looking great! 👌
[error] Xcode is not installed
```

**Comment by robingenz** [comment]
Feel free to test the new dev version and let me know if it works:

```
npm i @capacitor-firebase/authentication@0.2.0-dev.eeac0a7.1648649641
```
