### ISSUE TITLE
feat(authentication): support OAuth 2.0 scopes

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-firebase#32]
**Is your feature request related to a problem? Please describe.**
Firebase Authentication allows to specify additional OAuth 2.0 scopes. This is currently not possible with this plugin.

**Describe the solution you'd like**
Add support for OAuth 2.0 scopes.

**Comment by aliexalter** [comment]
@robingenz 

I would like to get oAuth access token to call REST photo library API. The plugin does not return credential.accessToken it only return credential.providerID, credential.idToken. I want to use oAuth access Token. 

From web implementation of firebase both signInWithPopup and signInWithRedirect return access token.

**Comment by robingenz** [comment]
> @robingenz
> 
> I would like to get oAuth access token to call REST photo library API. The plugin does not return credential.accessToken it only return credential.providerID, credential.idToken. I want to use oAuth access Token.
> 
> From web implementation of firebase both signInWithPopup and signInWithRedirect return access token.

@aliexalter Please create a new issue and share some more information (like the selected authentication method).
