### ISSUE TITLE
bug(authentication): NPR reported by Firebase Crashlytics

### ISSUE THREAD

**Issue by erikwalle** [robingenz/capacitor-firebase#37]
**Plugin version:**
0.3.11
^ Will update to the latest and update if no longer occurring.

**Platform(s):**
Reported on: ASUS_Z012DC

**Current behavior:**
Can't reproduce the bug so far, working from a crashlytics report.

**Other information:**

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.getcapacitor.PluginCall.resolve(com.getcapacitor.JSObject)' on a null object reference
dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication$3.onComplete (FirebaseAuthentication.java:185)
com.google.android.gms.tasks.zzj.run (Unknown Source:4)
android.os.Handler.handleCallback (Handler.java:789)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:169)
android.app.ActivityThread.main (ActivityThread.java:6578)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

**Comment by robingenz** [comment]
I am closing this issue as there is nothing new. However, I continue to keep an eye on it.
