### ISSUE TITLE
Documentation: Can analytics be used with Web?

### ISSUE THREAD

**Issue by ptmkenny** [robingenz/capacitor-firebase#48]
Thanks for writing this plugin!  I am attempting to migrate my Ionic React app, which uses [capacitor-community/firebase-analytics](https://github.com/capacitor-community/firebase-analytics), but I can't find the `initializeFirebase` function for PWAs.

It doesn't seem to be listed on the [docs page for Analytics](https://github.com/robingenz/capacitor-firebase/blob/main/packages/analytics/README.md#installation), either.

Is there a way to use this plugin with a PWA as well?

**Comment by robingenz** [comment]
Hi @ptmkenny,
yes, the Analytics plugin supports the web.
You just need to install the SDK and initialize Firebase as descibed here: https://firebase.google.com/docs/web/setup

```
npm install firebase
```

```ts
import { initializeApp } from 'firebase/app';

// TODO: Replace the following with your app's [Firebase project configuration](https://firebase.google.com/docs/web/learn-more#config-object)
const firebaseConfig = {
  //...
};

const app = initializeApp(firebaseConfig);
```

After that you can use the plugin.
I just added this info to the docs.
I may add a wrapper for this step to the `@capacitor-firebase/app` plugin in the future.

Let me know if you have more questions.
