### ISSUE TITLE
feat: support Firebase Cloud Messaging

### ISSUE THREAD

**Issue by robingenz** [robingenz/capacitor-firebase#5]
**Is your feature request related to a problem? Please describe:**

Firebase Cloud Messaging is not currently supported.

**Describe the solution you'd like:**

Add a Firebase Cloud Messaging plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by HeikoKanzler** [comment]
+1

(and thank you for the great work!)

**Comment by mesqueeb** [comment]
+1 ! currently I can't get push notifications on Android because of this issue for the `fcm` plugin:
https://github.com/capacitor-community/fcm/issues/99

so official support for FCM on `capacitor-firebase` would be really awesome!

**Comment by robingenz** [comment]
The first dev version is ready. 🎉  It would be great if someone could support me with testing.
I am happy about any feedback!

```
npm i @capacitor-firebase/messaging@0.2.1-dev.d4bafb5.1651696824
```

**Comment by mesqueeb** [comment]
Does the plugin work completely standalone or do we also need `@capacitor/push-notifications` installed as peer dependency?

**Comment by robingenz** [comment]
> Does the plugin work completely standalone or do we also need `@capacitor/push-notifications` installed as peer dependency?

completely standalone 👌

**Comment by robingenz** [comment]
To be more precise: You don't need the `@capacitor/push-notifications` plugin, but you can still use it in combination.
