### ISSUE TITLE
bug: screenClassOverride value showing incorrect in firebase console

### ISSUE THREAD

**Issue by AhammadAlisha** [robingenz/capacitor-firebase#50]
**Plugin(s):**

"@capacitor-firebase/analytics": "^0.1.1"
"firebase": "^9.6.5",

**Platform(s):**

Android

**Current behavior:**

I'm passing different values for screenName, screenClassOverride in setScreenName method. But in firebase console, i'm seeing firebase_screen_class value as firebase_screen.

**Expected behavior:**

firebase_screen_class should be taken from screenClassOverride

**Steps to reproduce:**

**Related code:**

const setScreenName = async () => {
  await FirebaseAnalytics.setCurrentScreen({
    screenName: 'Homepage',
    screenClassOverride: 'Home',
  })
}

**Other information:**

![screen1](https://user-images.githubusercontent.com/32287530/160581887-acc8c45a-105d-4260-b693-921c5981e8a0.jpg)
![screen2](https://user-images.githubusercontent.com/32287530/160581896-c26f4a29-dac5-4e12-bce5-8871d1472f85.jpg)

**Capacitor doctor:**

Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 3.4.3    
  @capacitor/core: 3.4.3   
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3    

Installed Dependencies:    

  @capacitor/core: 3.4.1   
  @capacitor/android: 3.4.0
  @capacitor/cli: 3.4.1    
  @capacitor/ios: 3.4.0

**Comment by robingenz** [comment]
Hi @AhammadAlisha,
thank you for your request.
I have just released a new version of `@capacitor-firebase/analytics` with fixes for `setCurrentScreen`:

```
npm i @capacitor-firebase/analytics@0.2.0
```

Please let me know if your issue persists.

**Comment by AhammadAlisha** [comment]
Hi @robingenz  thanks for the response.

issue still persists with @0.2.0

**Comment by robingenz** [comment]
Okay, found the issue.
Will be fixed in the next version.
I already released a dev version:

```
npm i @capacitor-firebase/analytics@0.2.0-dev.95e7bb6.1648580185
```
