### ISSUE TITLE
self authentication on android

### ISSUE THREAD

**Issue by MeirBen** [robingenz/capacitor-firebase#61]
Hi 
I had a problem with Android.
As soon as the SMS reaches the device, it performs native authentication behind the scenes,
And afterwards I can't authenticate to web layer JS SDK, because the OTP expired.
Is there a way to proceed with web authentication?

Thank you

**Comment by robingenz** [comment]
Hi @MeirBen,
thank you for your request!
From the Firebase docs:
```java
    @Override
    public void onVerificationCompleted(PhoneAuthCredential credential) {
        // This callback will be invoked in two situations:
        // 1 - Instant verification. In some cases the phone number can be instantly
        //     verified without needing to send or enter a verification code.
        // 2 - Auto-retrieval. On some devices Google Play services can automatically
        //     detect the incoming verification SMS and perform verification without
        //     user action.
        Log.d(TAG, "onVerificationCompleted:" + credential);

        signInWithPhoneAuthCredential(credential);
    }
```

> On some devices Google Play services can automatically detect the incoming verification SMS and perform verification without user action.

I have also found the following issue: https://github.com/firebase/quickstart-android/issues/296
It says that there are currently no plans to disable instant verification. I have not found any information about auto-retrieval either.
I guess there is nothing you can do about that unfortunately.
For this reason I close this issue.

**Comment by MeirBen** [comment]
Thank you for quick response!

I did notice now that is possible when setting the skipNativeAuth to true, it skip the auto-retrieval , and SignInWithCredentials for web layer works with manual verification code.
(I don't know if is also valid for instant verification though).

Is this the purpose of skipNativeAuth?

**Comment by robingenz** [comment]
Oh, yes, the purpose of `skipNativeAuth` is to be able to use the Firebase JS SDK. I should have asked you if you had set that, sorry. I am glad that it works now. 🎉
