### ISSUE TITLE
bug: Analytics - Error building iOS App

### ISSUE THREAD

**Issue by justinpathrose** [robingenz/capacitor-firebase#62]
**Plugin(s):**

@capacitor-firebase/analytics
version: 0.2.1

**Platform(s):**
iOS

**Current behavior:**
During the iOS App build process, we are getting this error ```No such module 'FirebaseCore'``` from FirebaseAnalytics.swift

**Expected behavior:**
iOS builds without error

**Steps to reproduce:**

Created a sample ionic react project with analytics plugin as a dependency. This can be viewed here - https://codesandbox.io/s/quirky-nova-vpymls

This is basic ionic react template and the iOS project is synced with the plugin. After trying to build from this iOS project, we are getting the build error 

```
No such module 'FirebaseCore'
```

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/core: 3.4.1
  @capacitor/android: 3.4.0
  @capacitor/ios: 3.4.0
  @capacitor/cli: 3.4.1
```

**Comment by justinpathrose** [comment]
Hi @robingenz,

Thanks for your time. 
Sorry, I had completely missed this change. This works for me now. 

Thanks again. I am closing this now.

**Comment by jongbonga** [comment]
Hi @robingenz 

Every time I do `cap sync` the pod update revert to `CapacitorFirebaseAnalytics`

**Comment by robingenz** [comment]
> Hi @robingenz
> 
> Every time I do `cap sync` the pod update revert to `CapacitorFirebaseAnalytics`

@jongbonga In that case you add the line in the wrong place.

```diff
target 'App' do
capacitor_pods
	# Add your Pods here
+  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
end
```

See https://github.com/robingenz/capacitor-firebase-plugin-demo/blob/d3237b0a3e4cc6a3fdd47f09d6b43c0057c61f18/ios/App/Podfile#L25

**Comment by jongbonga** [comment]
True... thanks
