### ISSUE TITLE
com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The sms code has expired. Please re-send the verification code to try again.

### ISSUE THREAD

**Issue by hathemi** [robingenz/capacitor-firebase#66]
the problem is This authentication happens in the background while the user still receives the verification code in an SMS. When the user tries to enter the verification code, i gets message that the verification code expired

```
V/Capacitor/FirebaseAuthenticationPlugin: Notifying listeners for event authStateChange
D/Capacitor/FirebaseAuthenticationPlugin: No listeners found for event authStateChange

E/FirebaseAuthentication: signInWithCredential failed.
com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The sms code has expired. Please re-send the verification code to try again.

```
how can i avoid receiving the verification code expiry message, and how can  i set up a listener for " authentication changes ." in vuejs??

please help!

**Comment by robingenz** [comment]
Hi @hathemi,

> how can i avoid receiving the verification code expiry message, and how can i set up a listener for " authentication changes ." in vuejs??

Please have a look at https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/README.md#addlistenerauthstatechange-

```ts
FirebaseAuthentication.addListener('authStateChange', (change) => {
	if (change.user) {
		// User logged in -> close the modal and navigate
	}
});
```

**Comment by hathemi** [comment]
thanks for reply! i will try it 
BUT, now i need to put the code received manually and compered it to  the verificationId when i click to button! 
is it possible to do that ?

**Comment by hathemi** [comment]
this only executed when i put the received code and call   
**await FirebaseAuthentication.signInWithPhoneNumber({    verificationId,    verificationCode,})**!!
```
  mounted() {
        FirebaseAuthentication.addListener('authStateChange', (change) => {
        if (change.user) {
		// User logged in -> close the modal and navigate
        }
      });
   },
```

is it posiible to disablle [SmsRetrieverHelper]!

**Comment by robingenz** [comment]
It fires every time a user's sign-in state changes.

**Comment by hathemi** [comment]
yes you're right! my fault
is there a way to disable **PhoneAuthProvider: Sms auto retrieval** ?

**Comment by robingenz** [comment]
Apparently yes. Another user had success by setting `skipNativeAuth` config option to false. He is using the Firebase JS SDK.
See https://github.com/robingenz/capacitor-firebase/issues/61#issuecomment-1087911228.

**Comment by hathemi** [comment]
https://github.com/robingenz/capacitor-firebase/issues/61#issuecomment-1087911228. 
following this link does the job.
