### ISSUE TITLE
bug: Basic config not returning token to app

### ISSUE THREAD

**Issue by sclawer** [robingenz/capacitor-firebase#67]
**Plugin(s):**

This is an Ionic-Capacitor app using Vue3 and Firebase Auth (only google)

**Platform(s):**

IOS specifically

**Current behavior:**

When deploying app and attempting login, the Native popup allows login, but the logfile shows the token being passed into the JS but the app is not updated as is expected

![IonicError](https://user-images.githubusercontent.com/40841372/162572662-dd0f3e4c-8c09-443a-9d18-b5d67c66e97a.png)

**Expected behavior:**

The expected behavour is that the user's Display Name is populated above the "Start with Ionic" banner

**Steps to reproduce:**

Bare Ionic app created with core functionality 

**Related code:**

I have created a stub with only google auth in the following Repo
https://github.com/sclawer/MobileApp.git

**Other information:**

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by robingenz** [comment]
Hi @sclawer,
please use the [`addListener('authStateChange', ...)`](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/README.md#addlistenerauthstatechange-) method to listen for the user's sign-in state changes.
(see https://github.com/sclawer/MobileApp/blob/96e5dec3833d5c4af55b32e41ca3879316d83283/src/views/HomePage.vue#L85).
Please also have a look at https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md if you want to login the user in the web layer to be able to use the firebase js sdk natively as well.

I am closing the issue as it does not seem to be a bug.

**Comment by sclawer** [comment]
It would be great if you had an example of the addListener in your demo app as a sample :)
