### ISSUE TITLE
bug: Error: There was an error while trying to get your package certificate hash

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase#70]
**Plugin(s):**

```
"@capacitor-firebase/authentication": "^0.2.1",
```

**Platform(s):**

android

**Current behavior:**

I have been using Twitter Auth on Android via `"skipNativeAuth": true,`
I had temporarily disabled this today: `"skipNativeAuth": false,` and it broke some signin methods.
So I had re-enabled it again.

Ever since then I cannot use twitter auth on android any more:
> Error: There was an error while trying to get your package certificate hash.
    at Object.cap.fromNative (VM3:411:32)
    at <anonymous>:1:18

I have cleaned the build folder. Double checked the certificate hash is registered on Firebase, double checked all Twitter requirements, but cannot seem to find the cause for this issue. : S

It won't go to the auth page even.

**Steps to reproduce:**

I can provide `aab` if required.

**Related code:**

```js
  async function signinWithTwitter(): Promise<void> {
    if (platform === 'android') {
      // 1. Create credentials on the native layer
      const result: SignInResult = await FirebaseAuthentication.signInWithTwitter()

      const { accessToken, secret } = result.credential || {}
      if (!accessToken || !secret) {
        throw new Error('twitter error')
      }

      // 2. Create credentials on the web layer
      const credential = TwitterAuthProvider.credential(accessToken, secret)
      // 3. Sign in on the web layer using the id token
      await signInWithCredential(firebaseAuth, credential)
    }
```

**Other information:**

<img width="651" alt="image" src="https://user-images.githubusercontent.com/3253920/163789532-01607521-090d-4bc1-b52f-76e3c25bab54.png">

**Capacitor doctor:**

```
npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by mesqueeb** [comment]
I realise that this is probably not related to this plugin, but I'm not sure what suddenly went wrong with the configuration of my app.

This is what happens on phone auth:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/3253920/163790799-aa6df66d-2d1a-41af-b252-12052fb36082.png">

and google auth:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/3253920/163791071-2921866f-52b0-4ccf-a4de-13bd22f1a4b4.png">


is it somehow connected to the wrong firebase project perhaps? Maybe the firebase auth instance is using the wrong projectId ?

**Comment by robingenz** [comment]
Hi @mesqueeb,
I'm doing my best to help you, these errors are annoying. 😄 
This seems like a duplicate of https://github.com/robingenz/capacitor-firebase-authentication/issues/97.

> I have cleaned the build folder. Double checked the certificate hash is registered on Firebase, double checked all Twitter requirements, but cannot seem to find the cause for this issue. 

I believe you. Please check it a third time. 

> is it somehow connected to the wrong firebase project perhaps? Maybe the firebase auth instance is using the wrong projectId ?

You have only one `google-services.json` file or? And it has the correct values?

**Comment by mesqueeb** [comment]
@robingenz thank you for the reply!!
I ended up doing these checks and finding the cause:
- double check my 2 related firebase apps > settings > android app > look at the SHA-1 and SHA-256 that were registered
- for both related projects make sure that **all** these keys were registered:
  - both **SHA-1** and **SHA-256** keys of my android keystore for uploading
  - both **SHA-1** and **SHA-256** keys of the app signing which are found on the Google Play console
  - both **SHA-1** and **SHA-256** keys of the Android Studio debug key that comes with the app (see [SO here](https://stackoverflow.com/a/39330177/2697506))

After registering these 6 keys in the Firebase console it worked again. 🎉  (I had some of these missing)
