### ISSUE TITLE
Question: Firestore

### ISSUE THREAD

**Issue by JuliusJacobitz** [robingenz/capacitor-firebase#91]
A little general question, but I cant get my head around it:

I am developing an ionic-vue ios and web app. I was able setup the authentication flow. Now I want to read data from the firestore. But I could not get it to work on ios. Calling `getDoc(doc(docRef,"docID"))` nothing happens on ios. It works on web tho.

Similar to [this](https://github.com/robingenz/capacitor-firebase-authentication/issues/78#issuecomment-924055336) I have tried the following:

```
function whichFirestore() {
  let store;
  if (Capacitor.isNativePlatform()) {
    store = initializeFirestore(firebaseApp, {});
  } else {
    store = getFirestore();
  }
  return store;
}
```

But it didn't change anything. Any suggestions what I am missing out?

**Comment by robingenz** [comment]
Hi @JuliusJacobitz,
Unfortunately I can't help you there, because I haven't gained much experience with Firestore in combination with Capacitor.
I may know more as soon as I get to this issue: https://github.com/robingenz/capacitor-firebase/issues/41
