### ISSUE TITLE
bug: Twitter auth provider cannot transition from native auth to Firebase JS SDK auth

### ISSUE THREAD

**Issue by agustinhaller** [robingenz/capacitor-firebase#99]
**Plugin(s):**
`@capacitor-firebase/authentication@0.3.0`

**Platform(s):**
iOS

**Current behavior:**
Twitter Auth Provider cannot transition from native auth to Firebase JS SDK auth.
The `FirebaseAuthentication.signInWithTwitter()` method returns no `result.credential.accessToken` nor `result.credential.secret` (both `undefined`). Thus I'm unable to get the `OAuthCredential` using `const nativeCredential = TwitterAuthProvider.credential(result.credential?.accessToken, result.credential?.secret)` in order to perform the authentication on the web layer with `signInWithCredential(auth, nativeCredential)`.

**Expected behavior:**
Twitter auth provider returns credential.accessToken and credential.secret (like it does on Android) and we can use those to perform the authentication on the web layer with `signInWithCredential(auth, nativeCredential)`.

**Steps to reproduce:**
I followed the steps mentioned in the [How to use this plugin with the Firebase JavaScript SDK guide](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md#examples).

**Related code:**
But as the Twitter example is missing I used the following (based on the other examples)
``` typescript
const signInWithTwitter = async () => {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithTwitter();
  // 2. Sign in on the web layer using the access token
  const credential = TwitterAuthProvider.credential(result.credential?.accessToken, result.credential?.secret);
  const auth = getAuth();
  await signInWithCredential(auth, credential);
};
```

**Other information:**
My project is working fine on Android and the web.
On iOS I got these errors on the Safari DevTools console:
- FirebaseError: Firebase: Error (auth/argument-error).
- null is not an object (evaluating 'credential._getIdTokenResponse')

This is the way I'm initializing the `@angular/fire` library in my NgModule according to [this comment](https://github.com/robingenz/capacitor-firebase/issues/56#issuecomment-1084991106) and [this comment](https://forum.ionicframework.com/t/firebase-auth-in-sdk-9-does-not-work-on-ios-sim-or-devices/215362/12?u=agustinhaller):
``` typescript
...

provideFirebaseApp(() => {
    const app = initializeApp(environment.firebase);

    if (Capacitor.isNativePlatform()) {
      initializeAuth(app, {
        persistence: indexedDBLocalPersistence
      });
    }
    return app;
  }),
  provideAuth(() => getAuth())

...
```

I also tried this alternate init with no luck. I don't believe this is the cause anyway:
``` typescript
provideFirebaseApp(() => initializeApp(environment.firebase)),
provideAuth(() => {
  if (Capacitor.isNativePlatform()) {
    return initializeAuth(getApp(), {
      persistence: indexedDBLocalPersistence
    });
  } else {
    return getAuth();
  }
}),
```

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/ios: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/core: 3.5.1

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

**Comment by robingenz** [comment]
Thank you for your request. I will have a look at it next week.

**Comment by agustinhaller** [comment]
@robingenz thank you so much for taking the time to look at this 🙏

**Comment by robingenz** [comment]
Okay, i found the issue and fixed it.
You can give it a try if you want:
```
npm i @capacitor-firebase/authentication@0.3.0-dev.2c2ae36.1654944437
```

I will release this fix in a few days.

Thank you for the report @agustinhaller !

**Comment by emilkaiser** [comment]
Nice, thanks!

Just a heads up, this won't work if you follow the instructions [here](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md) since `skipNativeAuth=true` causes `handleSuccessfulSignIn` to return early.

**Comment by robingenz** [comment]
@emilkaiser That's correct! The Firebase JS SDK has it's own `accessToken` property (see [here](https://firebase.google.com/docs/reference/js/auth.oauthcredential?hl=en#properties)).

**Comment by robingenz** [comment]
@emilkaiser Have you tried the following?

```ts
const signInWithTwitter = async () => {
  // 1. Create credentials on the native layer
  const result = await FirebaseAuthentication.signInWithTwitter();
  // 2. Sign in on the web layer using the id token and nonce
  const provider = new OAuthProvider('twitter.com');
  const credential = provider.credential({
    idToken: result.credential?.idToken,
  });
  // Print access token - Does this work?
  console.log(credential.accessToken);
  // ...
};
```

Is `credential.accessToken` set?

**Comment by emilkaiser** [comment]
To be clear, `result.credential` is `{ providerId: 'twitter.com' }`, no IdToken when `skipNativeAuth=true`.

**Comment by robingenz** [comment]
> To be clear, `result.credential` is `{ providerId: 'twitter.com' }`, no IdToken when `skipNativeAuth=true`.

I have never tested Twitter SignIn with `skipNativeAuth=true`, but there should actually be an `idToken` included. If not, please create a new issue and I will take a look.
